#!/bin/bash

LC_ALL=sv_SE locale language
LC_ALL=sv_SE locale charmap
LC_ALL=sv_SE locale int_curr_symbol
LC_ALL=sv_SE locale int_prefix

setxkbmap -model pc104 -layout se
#localectl set-locale LANG="sv_SE.ISO-8859-1" LC_CTYPE="sv_SE"
